refactor: improved scripts

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -5,17 +5,16 @@ set -euo pipefail
 
 IC_WASM_VERSION="0.9.0"
 
-SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "$SCRIPTS_DIR/.."
 
 function run() {
-    1>&2 echo "running $@"
-    rc=0 && "$@" || rc="$?"
-    if ! [ "$rc" -eq 0 ]
-    then
-        1>&2 echo "Bootstrap command failed: $@"
-        exit "$rc"
-    fi
+  echo 1>&2 "running $@"
+  rc=0 && "$@" || rc="$?"
+  if ! [ "$rc" -eq 0 ]; then
+    echo 1>&2 "Bootstrap command failed: $@"
+    exit "$rc"
+  fi
 }
 
 rust_version=$(cat ./rust-toolchain.toml | sed -n 's/^channel[[:space:]]*=[[:space:]]"\(.*\)"/\1/p')
@@ -25,10 +24,9 @@ echo "using rust version '$rust_version'"
 run curl --fail https://sh.rustup.rs -sSf | run sh -s -- -y --default-toolchain "none" --no-modify-path
 
 echo "looking for ic-wasm $IC_WASM_VERSION"
-if [[ ! "$(command -v ic-wasm)" || "$(ic-wasm --version)" != "ic-wasm $IC_WASM_VERSION" ]]
-then
-    echo "installing ic-wasm $IC_WASM_VERSION"
-    run cargo install ic-wasm --version $IC_WASM_VERSION --locked
+if [[ ! "$(command -v ic-wasm)" || "$(ic-wasm --version)" != "ic-wasm $IC_WASM_VERSION" ]]; then
+  echo "installing ic-wasm $IC_WASM_VERSION"
+  run cargo install ic-wasm --version $IC_WASM_VERSION --locked
 fi
 
 echo "installing candid-extractor"
diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,163 +1,150 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-set -x
 
 IC_WASM_VERSION="0.9.0"
 
 # Make sure we always run from the root
-SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-cd "$SCRIPTS_DIR/.."
+SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+PROJECT_ROOT="$SCRIPTS_DIR/.."
 
-#########
-# USAGE #
-#########
+cd $PROJECT_ROOT
 
-function title() {
-    echo "Builds Solana Canisters"
+# Display the script title
+title() {
+  echo -e "Builds IC Solana Canister"
 }
 
-function usage() {
-    cat << EOF
+usage() {
+  cat <<EOF
 
 Usage:
   $0 [--only-dependencies] [--rpc] [--wallet]
 
 Options:
-  --only-dependencies   only build rust dependencies (no js build, no wasm optimization)
-  --rpc                 build the rpc canister
-  --wallet              build the wallet canister
+  --only-dependencies     only build rust dependencies (no js build, no wasm optimization)
+  --rpc                   build the rpc canister
+  --wallet                build the wallet canister
+  -h, --help              Show this help message
 EOF
 }
 
-function help() {
-    cat << EOF
+help() {
+  cat <<EOF
 
-Builds the Solana RPC or Solana Wallet canister.
+Builds the IC Solana canisters.
 
 NOTE: This requires a working rust toolchain as well as ic-wasm.
 EOF
-
 }
+
+# Function to build a single canister
+# Arguments:
+#   $1 - Canister name (e.g., ic-solana-rpc)
+#   $2... - Extra cargo build arguments
+build_canister() {
+  local canister=$1
+  shift
+  local extra_build_args=("$@")
+
+  local src_dir="$PROJECT_ROOT/src/$canister"
+  local target="wasm32-unknown-unknown"
+  local cargo_home="${CARGO_HOME:-"$HOME/.cargo"}"
+  local rustflags="--remap-path-prefix $cargo_home=/cargo -C link-args=-zstack-size=3000000"
+  local cargo_target_dir="${CARGO_TARGET_DIR:-"$PROJECT_ROOT/target"}"
+
+  # Prepare cargo build arguments
+  local cargo_build_args=(
+    --manifest-path "$src_dir/Cargo.toml"
+    --target "$target"
+    --release
+    --locked
+  )
+
+  # Append any extra build arguments
+  if [[ ${#extra_build_args[@]} -gt 0 ]]; then
+    cargo_build_args+=("${extra_build_args[@]}")
+  fi
+
+  echo "Running cargo build for '$canister' with arguments: ${cargo_build_args[*]}"
+  echo "RUSTFLAGS: $rustflags"
+
+  RUSTFLAGS="$rustflags" cargo build "${cargo_build_args[@]}"
+
+  # If only dependencies are to be built, exit here
+  if [[ -n "$ONLY_DEPS" ]]; then
+    echo "Dependencies built for '$canister'."
+    return
+  fi
+
+  # Retrieve package version using jq
+  local package_version
+  package_version=$(cargo metadata --format-version=1 --no-deps |
+    jq -r --arg name "$canister" '.packages[] | select(.name == $name) | .version') || true
+
+  if [[ -z "$package_version" ]]; then
+    error_exit "Failed to retrieve version for package '$canister'. Ensure that the Cargo.toml is correctly configured."
+  fi
+
+  # Optimize wasm and set metadata
+  ic-wasm "$cargo_target_dir/$target/release/${canister}.wasm" -o "./$canister.wasm" shrink
+  ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:service -f "$src_dir/$canister.did" -v public
+
+  # # indicate support for certificate version 1 and 2 in the canister metadata
+  # ic-wasm "$canister.wasm" -o "$canister.wasm" metadata supported_certificate_versions -d "1,2" -v public
+
+  if [ -n "$package_version" ]; then
+    ic-wasm "$canister.wasm" -o "$canister.wasm" metadata app:version -d "$package_version" -v public
+  fi
+
+  case "$canister" in
+  ic-solana-rpc | ic-solana-wallet)
+    ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:args -d "(InitArgs)" -v public
+    ;;
+  esac
+
+  gzip --no-name --force "$canister.wasm"
+
+  echo "Done"
+}
+
+# Checking for dependencies
+if [[ ! "$(command -v ic-wasm)" || "$(ic-wasm --version)" != "ic-wasm $IC_WASM_VERSION" ]]; then
+  echo "could not find ic-wasm $IC_WASM_VERSION"
+  echo "ic-wasm version $IC_WASM_VERSION is needed, please run the following command:"
+  echo " cargo install ic-wasm --version $IC_WASM_VERSION"
+  exit 1
+fi
 
 ONLY_DEPS=
 CANISTERS=()
 
-while [[ $# -gt 0  ]]
-do
-    case "$1" in
-        -h|--help)
-            title
-            usage
-            help
-            exit 0
-            ;;
-        --only-dependencies)
-            ONLY_DEPS=1
-            shift
-            ;;
-        --rpc)
-            CANISTERS+=("ic-solana-rpc")
-            shift
-            ;;
-        --wallet)
-            CANISTERS+=("ic-solana-wallet")
-            shift
-            ;;
-        *)
-            echo "ERROR: unknown argument $1"
-            usage
-            echo
-            echo "Use 'build --help' for more information"
-            exit 1
-            ;;
-    esac
-done
-
-# build rpc by default
-if [ ${#CANISTERS[@]} -eq 0 ]; then
-    CANISTERS=("ic-solana-rpc")
-fi
-
-# Checking for dependencies
-if [[ ! "$(command -v ic-wasm)" || "$(ic-wasm --version)" != "ic-wasm $IC_WASM_VERSION" ]]
-then
-    echo "could not find ic-wasm $IC_WASM_VERSION"
-    echo "ic-wasm version $IC_WASM_VERSION is needed, please run the following command:"
-    echo "  cargo install ic-wasm --version $IC_WASM_VERSION"
-    exit 1
-fi
-
-# Builds a single canister
-# build_canister CANISTER EXTRA_BUILD_ARGS...
-# CANISTER: possible values: [ic-solana-rpc, ic-solana-wallet]
-# EXTRA_BUILD_ARGS: extra arguments supplied to cargo when building the canister
-function build_canister() {
-    local canister=$1
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+  -h | --help)
+    title
+    usage
+    help
+    exit 0
+    ;;
+  --only-dependencies)
+    ONLY_DEPS=1
     shift
-    local extra_build_args=("$@")
-
-    echo "Building $canister"
+    ;;
+  --rpc)
+    build_canister "ic-solana-rpc"
+    shift
+    ;;
+  --wallet)
+    build_canister "ic-solana-wallet"
+    shift
+    ;;
+  *)
+    echo "ERROR: unknown argument $1"
+    usage
     echo
-
-    SRC_DIR="$PWD/src/$canister"
-    TARGET="wasm32-unknown-unknown"
-    # standardize source references
-    CARGO_HOME="${CARGO_HOME:-"$HOME/.cargo"}"
-    RUSTFLAGS="--remap-path-prefix $CARGO_HOME=/cargo -C link-args=-zstack-size=3000000"
-
-    cargo_build_args=(
-        --manifest-path "$SRC_DIR/Cargo.toml"
-        --target "$TARGET"
-        --release
-        --locked
-        )
-    # XXX: for bash > 4.4, empty arrays are considered unset, so do some substitution
-    cargo_build_args+=(${extra_build_args[@]+"${extra_build_args[@]}"})
-
-    echo Running cargo build "${cargo_build_args[@]}"
-    echo RUSTFLAGS: "$RUSTFLAGS"
-
-    RUSTFLAGS="$RUSTFLAGS" cargo build "${cargo_build_args[@]}"
-
-    if [ "$ONLY_DEPS" != "1" ]
-    then
-        CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$SRC_DIR/../../target/}"
-
-      package_version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.name == "'$canister'") | .version')
-
-      # Optimize WASM and set metadata
-
-      echo Optimising wasm
-      ic-wasm "$CARGO_TARGET_DIR/$TARGET/release/${canister}.wasm" -o "./$canister.wasm" shrink
-#      ic-wasm "$canister.wasm" -o "./$canister.wasm" optimize O3
-
-      echo Adding wasm metadata: \"candid:service\"
-      ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:service -f "$SRC_DIR/$canister.did" -v public
-
-      if [ -n "$package_version" ]; then
-        echo Adding wasm metadata: \"app:version\"
-        ic-wasm "$canister.wasm" -o "$canister.wasm" metadata app:version -d "$package_version" -v public
-      fi
-
-#      # indicate support for certificate version 1 and 2 in the canister metadata
-#      ic-wasm "$canister.wasm" -o "$canister.wasm" metadata supported_certificate_versions -d "1,2" -v public
-
-      if [ "$canister" == "ic-solana-rpc" ]
-      then
-        ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:args -d "(InitArgs)" -v public
-      fi
-
-      if [ "$canister" == "ic-solana-wallet" ]
-      then
-        ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:args -d "(InitArgs)" -v public
-      fi
-
-      gzip --no-name --force "$canister.wasm"
-    fi
-}
-
-for canister in "${CANISTERS[@]}"
-do
-    build_canister "$canister"
+    echo "Use 'build --help' for more information"
+    exit 1
+    ;;
+  esac
 done
diff --git a/scripts/did b/scripts/did
--- a/scripts/did
+++ b/scripts/did
@@ -1,37 +1,35 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-set -x
 
 function generate_did() {
   local canister=$1
   canister_root="src/$canister"
 
   cargo build --manifest-path="$canister_root/Cargo.toml" \
-      --target wasm32-unknown-unknown \
-      --release --package "$canister"
+    --target wasm32-unknown-unknown \
+    --release --package "$canister"
 
   local target_dir="${CARGO_TARGET_DIR:-target}"
   local wasm_path="$target_dir/wasm32-unknown-unknown/release/${canister}.wasm"
 
   if [[ ! -f "$wasm_path" ]]; then
-      echo "WASM file not found: $wasm_path"
-      exit 1
+    echo "WASM file not found: $wasm_path"
+    exit 1
   fi
 
-  candid-extractor "$wasm_path" > "$canister_root/$canister.did"
+  candid-extractor "$wasm_path" >"$canister_root/$canister.did"
 }
 
 # Check if at least one argument is provided
 if [[ $# -lt 1 ]]; then
-    echo "Usage: $0 ic-solana-rpc,ic-solana-wallet,..."
-    exit 1
+  echo "Usage: $0 ic-solana-rpc,ic-solana-wallet,..."
+  exit 1
 fi
 
 # The list of canisters of your project
 CANISTERS=$1
 
-for canister in $(echo $CANISTERS | sed "s/,/ /g")
-do
-    generate_did "$canister"
+for canister in $(echo $CANISTERS | sed "s/,/ /g"); do
+  generate_did "$canister"
 done
diff --git a/scripts/docker-build b/scripts/docker-build
--- a/scripts/docker-build
+++ b/scripts/docker-build
@@ -1,98 +1,133 @@
 #!/usr/bin/env bash
-# vim: ft=bash
-# Build Solana inside docker. This outputs ic-solana-rpc.wasm.gz.
 
-set -euo pipefail
+set -eEuo pipefail
 
-# Make sure we always run from the root
-SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-cd "$SCRIPTS_DIR/.."
+SCRIPT_NAME=$(basename "$0")
+ARTIFACTS_DIR="./artifacts"
+BUILD_MODE=${BUILD_MODE:-"production"}
 
-function title() {
-    echo "Build Solana inside Docker"
+title() {
+  echo -e "IC Solana Reproducible Builds"
 }
 
 function usage() {
-    cat << EOF
+  cat <<EOF
 
 Usage:
-  $0
+  ${SCRIPT_NAME} [OPTIONS]
 
+Options:
+  --rpc         Build the RPC canister
+  --wallet      Build the Wallet canister
+
+  -h, --help    Show this help message
 EOF
 }
 
 function help() {
-    cat << EOF
+  cat <<EOF
 
-This will create (and override) "./ic-solana-rpc.wasm.gz".
+Helper script to facilitate the building of the canisters in the IC Solana project in a reproducible way.
+
+NOTE: This requires a working Docker installation.
 EOF
 }
 
-## Building
-
-function build() {
-    local canister="$1"
-
-    # image name and build args, made global because they're used in
-    # check_feature()
-    image_name="ic-solana-docker-build"
-    docker_build_args=( --target "scratch_${canister//-/_}" )
-
-    docker_build_args+=(--tag "$image_name" .)
-
-    echo "The following image name will be used: $image_name"
-
-    tmp_outdir=$(mktemp -d)
-
-    set -x
-    DOCKER_BUILDKIT=1 docker build \
-        "${docker_build_args[@]}" \
-        --output "$tmp_outdir"
-    set +x
-
-    echo "Copying build output from $tmp_outdir to $PWD"
-    cp "$tmp_outdir/$canister.wasm.gz" .
-
-    echo "Removing $tmp_outdir"
-    rm -rf "$tmp_outdir"
+exec_function() {
+  local function_name="$1"
+  shift
+  echo "------------------------------------------------------"
+  echo -e "\033[1mSTART:\033[0m $function_name"
+  "$function_name" "$@"
+  echo -e "\033[1mCOMPLETED:\033[0m $function_name"
 }
 
-# ARGUMENT PARSING
+# Check if Docker is installed
+check_docker() {
+  if ! command -v docker &>/dev/null; then
+    echo "ERROR: Docker is not installed or not in PATH." >&2
+    exit 1
+  fi
 
-CANISTERS=()
-while [[ $# -gt 0 ]]
-do
-    case $1 in
-        -h|--help)
-            title
-            usage
-            help
-            exit 0
-            ;;
-        --rpc)
-            CANISTERS+=("ic-solana-rpc")
-            shift
-            ;;
-        --wallet)
-            CANISTERS+=("ic-solana-wallet")
-            shift
-            ;;
-        *)
-            echo "ERROR: unknown argument $1"
-            usage
-            echo
-            echo "Use '$0 --help' for more information"
-            exit 1
-            ;;
-    esac
-done
+  if ! docker info >/dev/null 2>&1; then
+    echo "ERROR: Docker daemon is not running or you don't have permissions." >&2
+    exit 1
+  fi
+}
 
-# build solana rpc by default
-if [ ${#CANISTERS[@]} -eq 0 ]; then
-    CANISTERS=("ic-solana-rpc")
+#############################################
+# FEATURES                                  #
+#############################################
+
+function build() {
+  local project_name=$1
+  local target=$2
+
+  echo "Building the '$project_name' canister in '$BUILD_MODE' mode..."
+
+  # Build the canister
+  docker build --build-arg BUILD_MODE=$BUILD_MODE -t ic-solana-$project_name --target $target .
+
+  local container_id
+  container_id=$(docker create "ic-solana-${project_name}")
+
+  # Ensure the artifacts directory exists
+  mkdir -p "${ARTIFACTS_DIR}/${project_name}"
+
+  # Copy artifacts from the container to the host
+  docker cp "${container_id}:/code/artifacts/." "${ARTIFACTS_DIR}/${project_name}/"
+
+  # Clean up the container
+  docker rm "$container_id"
+
+  # Remove the Docker image to save space
+  docker rmi "ic-solana-${project_name}" --force
+
+  echo "Artifacts for '$project_name' have been copied to '${ARTIFACTS_DIR}/${project_name}/'"
+}
+
+function build_rpc() {
+  build rpc build_rpc
+}
+
+function build_wallet() {
+  build wallet build_wallet
+}
+
+#############################################
+# SCRIPT OPTIONS                            #
+#############################################
+
+if [[ $# -eq 0 ]]; then
+  title
+  usage
+  exit 0
 fi
 
-for canister in "${CANISTERS[@]}"
-do
-    build "$canister"
+check_docker
+
+# Parse command-line arguments
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+  -h | --help)
+    title
+    usage
+    help_info
+    exit 0
+    ;;
+  --rpc)
+    exec_function build_rpc
+    shift
+    ;;
+  --wallet)
+    exec_function build_wallet
+    shift
+    ;;
+  *)
+    echo -e "ERROR: Unknown argument '$1'" >&2
+    usage
+    echo -e "\nUse '${SCRIPT_NAME} --help' for more information." >&2
+    exit 1
+    ;;
+  esac
 done
diff --git a/scripts/version b/scripts/version
--- a/scripts/version
+++ b/scripts/version
@@ -9,46 +9,42 @@
 set -euo pipefail
 
 log() {
-    >&2 echo "version: $@"
+  echo >&2 "version: $@"
 }
 
 # First, figure out the commit and error out if we can't
 commit=$(git rev-parse HEAD)
-if [[ -z $commit ]]
-then
-    log "no commit found"
-    exit 1
+if [[ -z $commit ]]; then
+  log "no commit found"
+  exit 1
 else
-    log "found commit '$commit'"
+  log "found commit '$commit'"
 fi
 
 # Try to infer the release based on either local git setup or CI environment
 release=
-if [[ -n ${CI:-} && ${GITHUB_REF_TYPE:-} == "tag" && ${GITHUB_REF_NAME:-} == release-* ]]
-then
-    release=${GITHUB_REF_NAME:-}
+if [[ -n ${CI:-} && ${GITHUB_REF_TYPE:-} == "tag" && ${GITHUB_REF_NAME:-} == release-* ]]; then
+  release=${GITHUB_REF_NAME:-}
 else
-    # grep may fail so we may just print an empty line (like 'true', really)
-    # NOTE: '|' has higher precedence than '||'
-    release=$(git tag --points-at "$commit" | grep '^release-' | head -n1 || echo -n "")
+  # grep may fail so we may just print an empty line (like 'true', really)
+  # NOTE: '|' has higher precedence than '||'
+  release=$(git tag --points-at "$commit" | grep '^release-' | head -n1 || echo -n "")
 fi
 
-if [[ -z $release ]]
-then
-    log "no release found for commit '$commit'"
+if [[ -z $release ]]; then
+  log "no release found for commit '$commit'"
 else
-    log "found release '$release'"
+  log "found release '$release'"
 fi
 
 # Figure out if the workspace is dirty
 dirty=
-if [ -n "$(git status --porcelain)" ]
-then
-    log "commit is dirty"
-    dirty="dirty"
+if [ -n "$(git status --porcelain)" ]; then
+  log "commit is dirty"
+  dirty="dirty"
 else
-    log "commit is clean"
-    dirty="clean"
+  log "commit is clean"
+  dirty="clean"
 fi
 
 echo "$commit,$release,$dirty"
